# 开发环境配置
mypet:
  db:
    host: 127.0.0.1
    port: 1800
    user: postgres
    password: mypg123abc
  base-url: http://localhost:8080
  upload:
    path: F:/MyWorkspace/project/mypet/uploads

logging:
  level:
    app.xinqianmao.com: DEBUG
