# 生产环境配置
mypet:
  db:
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  base-url: ${BASE_URL}
  upload:
    path: ${UPLOAD_PATH}

logging:
  level:
    app.xinqianmao.com: WARN
    root: WARN
